services:
  ao-cu:
    image: ghcr.io/permaweb/ao-cu:latest
    volumes:
      - ${CU_WALLET_FILE:-./test-wallet.json}:/usr/app/test-wallet.json
    ports:
      - ${CU_PORT:-6363}:${CU_PORT:-6363}
    environment:
      PORT: ${CU_PORT:-6363}
      WALLET_FILE: ${CU_WALLET_FILE:-./test-wallet.json}
      NODE_CONFIG_ENV: ${NODE_CONFIG_ENV:-development}
      NODE_HEAPDUMP_OPTIONS: ${NODE_HEAPDUMP_OPTIONS:-nosignal}
      PROCESS_CHECKPOINT_TRUSTED_OWNERS: ${PROCESS_CHECKPOINT_TRUSTED_OWNERS:-ivDvfMaelSjkht7rbuGSOEjSz3HMe4Unw2GdyAUEeCM}
      GRAPHQL_URL: ${GRAPHQL_URL:-https://arweave.net/graphql}
      CHECKPOINT_GRAPHQL_URL: ${CHECKPOINT_GRAPHQL_URL:-https://arweave.net/graphql}
      PROCESS_WASM_MEMORY_MAX_LIMIT: ${PROCESS_WASM_MEMORY_MAX_LIMIT:-17179869184}
      CHECKPOINT_VALIDATION_STEPS: ${CHECKPOINT_VALIDATION_STEPS:-1}
      CHECKPOINT_VALIDATION_THRESH: ${CHECKPOINT_VALIDATION_THRESH:-0}
      CHECKPOINT_VALIDATION_RETRIES: ${CHECKPOINT_VALIDATION_RETRIES:-1}
