name: Build and Test

on: [pull_request]

jobs:
  # TODO: add unit tests using bused
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.2
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - run: yarn --frozen-lockfile
      - run: yarn aos:build
      - run: yarn test
