name: Build and Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - develop
      - main

jobs:
  unit:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        name: Check out repository code

      - name: Setup Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: '5.3' # Specify the Lua version you need

      - name: Setup LuaRocks

        uses: leafo/gh-actions-luarocks@v4.3.0

      - name: Install Busted
        run: luarocks install ar-io-ant-registry-0.1-1.rockspec

      - name: Run Busted Tests
        run: busted .

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.2
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - run: yarn --frozen-lockfile
      - run: yarn aos:build
      - run: yarn test:integration
  evolve:
    # Run on main branch only
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main'
    needs: [integration, unit]
    environment: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.2
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - run: yarn evolve
        env:
          WALLET: ${{ secrets.WALLET }}
          REGISTRY_ID: ${{ vars.REGISTRY_ID }}
          VAOT_ID: ${{ vars.VAOT_ID}}
      - name: Notify Success
        if: success()
        uses: rtCamp/action-slack-notify@v2.3.0
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: Update Proposed to ANT Registry Process!
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CUSTOM_PAYLOAD: |
            {
              "attachments": [{
                "fallback": "Update Proposed for ANT Registry!",
                "color": "good",
                "title": "Details",
                "text": 'The ANT Registry ${{ github.ref_name == 'main' && 'Testnet' || 'Devnet' }} Process has an update Proposal!',
                "fields": [{
                  "title": "Network",
                  "value": "${{ github.ref_name == 'main' && 'testnet' || 'devnet' }}",
                  "short": true
                },
                {
                  "title": "Process ID",
                  "value": "${{ vars.REGISTRY_ID }}",
                  "short": true
                },
                {
                  "title": "View on ao.link",
                  "value": "https://www.ao.link/#/entity/${{ vars.REGISTRY_ID }}?tab=source-code",
                  "short": false
                },
                 {
                  "title": "Vote on this proposal in VAOT",
                  "value": "https://vaot.ar.io/#/${{ vars.VAOT_ID }}",
                  "short": false
                },
                {
                  "title": "Commit",
                  "value": "<https://github.com/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>"
                }
                ]
              }]
            }

      - name: Notify Failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: danger
          SLACK_TITLE: ANT Registry Process update Proposal FAILED!
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CUSTOM_PAYLOAD: |
            {
              "text": "ANT Registry Process Proposal Failed!",
              "attachments": [{
                "fallback": "Failed to propose update to ANT Registry!",
                "color": "danger",
                "title": "Details",
                "text": 'The ANT Registry ${{ github.ref_name == 'main' && 'Testnet' || 'Devnet' }} Process FAILED to create an update Proposal!',
                "fields": [{
                  "title": "Network",
                  "value": "${{ github.ref_name == 'main' && 'testnet' || 'devnet' }}",
                  "short": true
                },
                {
                  "title": "Process ID",
                  "value": "${{ vars.REGISTRY_ID }}",
                  "short": true
                },
                {
                  "title": "GitHub Action",
                  "value": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                  "short": false
                },
                {
                  "title": "Commit",
                  "value": "<https://github.com/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>"
                }
                ]
              }]
            }
